In [1]:
import boto3
from dotenv import load_dotenv
import os

load_dotenv()

True

In [ ]:
s3 = boto3.client(
    "s3",
    region_name=os.getenv("AWS_REGION"),
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
)
bucket = os.getenv("S3_BUCKET_NAME")

print("Connected!")

Connected!


In [3]:
with open("hello.txt", "w") as f:
    f.write("Hello S3")

In [4]:
s3.upload_file("hello.txt", bucket, "test/hello.txt")
print("Upload success")

Upload success


In [11]:
s3.download_file(bucket, "test/hello.txt", "download.txt")
with open("download.txt") as f:
    print(f.read())

ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

In [6]:
import numpy as np

arr = np.random.rand(5, 5)

np.save("matrix.npy", arr)

In [7]:
s3.upload_file(
    "matrix.npy",
    bucket,
    "test/matrix.npy"
)

In [8]:
response = s3.get_object(
    Bucket=bucket,
    Key="test/matrix.npy"
)

raw_bytes = response["Body"].read()

print(type(raw_bytes))

<class 'bytes'>


In [9]:
import io

buffer = io.BytesIO(raw_bytes)

loaded = np.load(buffer)

print(loaded)

[[0.15021756 0.88035039 0.18565769 0.0341691  0.64029786]
 [0.89197925 0.86226966 0.69184098 0.53268954 0.33804332]
 [0.24712141 0.12990486 0.15683599 0.1357074  0.75252889]
 [0.78116665 0.74948749 0.86432629 0.02975954 0.13193786]
 [0.78353134 0.73709627 0.78799181 0.21107487 0.21841497]]


In [10]:
s3.delete_object(
    Bucket=bucket,
    Key="test/hello.txt"
)

print("Deleted hello.txt")

Deleted hello.txt


In [13]:
s3.delete_object(
    Bucket=bucket,
    Key="test/matrix.npy"
)

print("Deleted matrix.npy")

Deleted matrix.npy


In [14]:
response = s3.list_objects_v2(
    Bucket=bucket
)

for obj in response.get("Contents", []):
    print(obj["Key"])

ml-data/dmfm_predictions/test/h1/R_pred_meta.csv
ml-data/dmfm_predictions/test/h1/R_pred_series.npy
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000000.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000001.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000002.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000003.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000004.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000005.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000006.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000007.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000008.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000009.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000010.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000011.npz
ml-data/dmfm_predictions

In [15]:
from botocore.exceptions import ClientError

class MiniS3Client:

    def __init__(self):

        self.bucket = os.getenv("S3_BUCKET_NAME")

        self.client = boto3.client(
            "s3",
            region_name=os.getenv("AWS_REGION"),
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        )

    # =========================
    # PRESIGNED UPLOAD
    # =========================

    def presigned_upload_url(
        self,
        s3_key,
        expires_in=300,
        content_type=None
    ):

        params = {
            "Bucket": self.bucket,
            "Key": s3_key
        }

        if content_type:
            params["ContentType"] = content_type

        url = self.client.generate_presigned_url(
            "put_object",
            Params=params,
            ExpiresIn=expires_in
        )

        return url

    # =========================
    # PRESIGNED DOWNLOAD
    # =========================

    def presigned_download_url(
        self,
        s3_key,
        expires_in=3600
    ):

        return self.client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": self.bucket,
                "Key": s3_key
            },
            ExpiresIn=expires_in
        )

    # =========================
    # LIST KEYS
    # =========================

    def list_keys(self, prefix=""):

        paginator = self.client.get_paginator(
            "list_objects_v2"
        )

        keys = []

        for page in paginator.paginate(
            Bucket=self.bucket,
            Prefix=prefix
        ):

            for obj in page.get("Contents", []):

                keys.append(obj["Key"])

        return keys

    # =========================
    # EXISTS
    # =========================

    def key_exists(self, s3_key):

        try:
            self.client.head_object(
                Bucket=self.bucket,
                Key=s3_key
            )

            return True

        except ClientError as e:

            if e.response["Error"]["Code"] == "404":
                return False

            raise

    # =========================
    # LATEST KEY
    # =========================

    def get_latest_key(
        self,
        prefix,
        suffix=".npz"
    ):

        paginator = self.client.get_paginator(
            "list_objects_v2"
        )

        candidates = []

        for page in paginator.paginate(
            Bucket=self.bucket,
            Prefix=prefix
        ):

            for obj in page.get("Contents", []):

                if obj["Key"].endswith(suffix):

                    candidates.append(
                        (
                            obj["LastModified"],
                            obj["Key"]
                        )
                    )

        if not candidates:
            return None

        candidates.sort(
            key=lambda x: x[0],
            reverse=True
        )

        return candidates[0][1]

In [16]:
s3client = MiniS3Client()

In [17]:
with open("a.txt", "w") as f:
    f.write("A")

with open("b.txt", "w") as f:
    f.write("B")

In [18]:
s3client.client.upload_file(
    "a.txt",
    s3client.bucket,
    "demo/a.txt"
)

s3client.client.upload_file(
    "b.txt",
    s3client.bucket,
    "demo/b.txt"
)

In [22]:
keys = s3client.list_keys("demo")

print(keys)

['demo/a.txt', 'demo/b.txt']


In [24]:
print(
    s3client.key_exists("demo/a.txt")
)

True


In [26]:
print(
    s3client.key_exists("demo/not_found.txt")
)

False


In [28]:
url = s3client.presigned_download_url(
    "demo/a.txt"
)

print(url)

https://utraffic-data-bk-team.s3.amazonaws.com/demo/a.txt?AWSAccessKeyId=AKIA3XG5NKBDPZZHF4JR&Signature=LEnLWTuvR%2Fa99mpBsSjMcxpgUQc%3D&Expires=1778307617


In [29]:
upload_url = s3client.presigned_upload_url(
    "uploads/test_upload.txt",
    content_type="text/plain"
)

print(upload_url)

https://utraffic-data-bk-team.s3.amazonaws.com/uploads/test_upload.txt?AWSAccessKeyId=AKIA3XG5NKBDPZZHF4JR&Signature=Fp6%2BDSQtk7utrDJB6ZVG2iZh5Ig%3D&content-type=text%2Fplain&Expires=1778304320


In [31]:
import requests

data = b"Hello from presigned upload"

response = requests.put(
    upload_url,
    data=data,
    headers={
        "Content-Type": "text/plain"
    }
)

print(response.status_code)

200


In [33]:
print(
    s3client.key_exists(
        "uploads/test_upload.txt"
    )
)

True


In [34]:
import time

with open("model1.npz", "wb") as f:
    f.write(b"111")

with open("model2.npz", "wb") as f:
    f.write(b"222")

In [35]:
s3client.client.upload_file(
    "model1.npz",
    s3client.bucket,
    "ml-data/model_20260509_100000.npz"
)

In [37]:
s3client.client.upload_file(
    "model1.npz",
    s3client.bucket,
    "ml-data/model_20260509_100000.npz"
)

In [38]:
files_to_delete = [
    "demo/a.txt",
    "demo/b.txt",
    "uploads/test_upload.txt",
    "ml-data/model_20260509_100000.npz",
    "ml-data/model_20260509_100005.npz",
]

objects = [
    {"Key": key}
    for key in files_to_delete
]

response = s3client.client.delete_objects(
    Bucket=s3client.bucket,
    Delete={
        "Objects": objects
    }
)

print("Deleted files:")
for item in response.get("Deleted", []):
    print("-", item["Key"])

Deleted files:
- uploads/test_upload.txt
- ml-data/model_20260509_100005.npz
- demo/b.txt
- demo/a.txt
- ml-data/model_20260509_100000.npz


In [45]:
all_keys = s3client.list_keys("")

print("Remaining files in bucket:")

for key in all_keys:
    print(key)

Remaining files in bucket:
ml-data/dmfm_predictions/test/h1/R_pred_meta.csv
ml-data/dmfm_predictions/test/h1/R_pred_series.npy
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000000.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000001.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000002.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000003.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000004.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000005.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000006.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000007.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000008.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000009.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000010.npz
ml-data/dmfm_predictions/test/h1/bundles/dmfm_pred_test_h1_idx000011.n